### ISSUE TITLE
Код не запускается...

### ISSUE THREAD

**Issue by balalamba** [vladilenm/js-patterns-youtube#1]
Добрый день, спасибо за урок.
У меня проблема причину которой я не могу понять..
У меня Node v10.13.0
Но к примеру файл  1 creational/2_factory.js не запускается.
вот вывод консоли: 

`static list = {
                ^
SyntaxError: Unexpected token =
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10) .....`

Но даже если я модифицирую этот кусок на это -

`static list(){
return {
        simple: SimpleMembership,
        standard: StandardMembership,
        premium: PremiumMembership
      }
}.....`

Я получаю новую ошибку

`const member = new Membership(name)
                     ^
TypeError: Membership is not a constructor
    at MemberFactory.create (C:\Users\WKXH4646\Desktop\node\learning.js:31:22)
    at Object.<anonymous> (C:\Users\WKXH4646\Desktop\node\learning.js:43:13).....`

Я предполагаю что это может взяться из за отсутствия поддержки синтаксиса версией, но это мне кажется странным, всё же 10.13 относительно свежая....

**Comment by vladilenm** [comment]
Нужно обновить версию NodeJS до последней. Там уже 12.9.1. Тогда все будет работать
Это относительно новый синтаксис
